//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking_KristianJeremic_NETProgramutvecklare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int ID { get; set; }
        public int BookingID { get; set; }
        public bool Paid { get; set; }
        public System.DateTime LastDayToPay { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
